### ISSUE TITLE
Date of birth box

### ISSUE THREAD

**Issue by MohammedAbidNafi** [HacktivatorsMJ/Mental-Health#4]
2023-10-20 18:19:24.050 19857-19857 AndroidRuntime          com.hacktivators.mentalhealth        E  FATAL EXCEPTION: main
                                                                                                    Process: com.hacktivators.mentalhealth, PID: 19857
                                                                                                    java.lang.IllegalArgumentException: com.google.android.material.datepicker.MaterialDatePicker requires a value for the com.hacktivators.mentalhealth:attr/materialCalendarTheme attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
                                                                                                    	at com.google.android.material.resources.MaterialAttributes.resolveTypedValueOrThrow(MaterialAttributes.java:72)
                                                                                                    	at com.google.android.material.resources.MaterialAttributes.resolveOrThrow(MaterialAttributes.java:89)
                                                                                                    	at com.google.android.material.datepicker.SingleDateSelector.getDefaultThemeResId(SingleDateSelector.java:160)
                                                                                                    	at com.google.android.material.datepicker.MaterialDatePicker.getThemeResId(MaterialDatePicker.java:223)
                                                                                                    	at com.google.android.material.datepicker.MaterialDatePicker.onCreateDialog(MaterialDatePicker.java:229)
                                                                                                    	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:644)
                                                                                                    	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:558)
                                                                                                    	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by MohammedAbidNafi** [comment]
Thank you for pointing this out this has been fixed!!
