### ISSUE TITLE
Personalized yoga plan unable to generate

### ISSUE THREAD

**Issue by Fardeenahmed181** [HacktivatorsMJ/Mental-Health#7]
2023-10-22 08:16:33.956 15092-24415 AndroidRuntime          com.hacktivators.mentalhealth        E  FATAL EXCEPTION: OkHttp Dispatcher
                                                                                                    Process: com.hacktivators.mentalhealth, PID: 15092
                                                                                                    java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
                                                                                                    	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
                                                                                                    	at android.widget.Toast.getLooper(Toast.java:265)
                                                                                                    	at android.widget.Toast.<init>(Toast.java:250)
                                                                                                    	at android.widget.Toast.makeText(Toast.java:865)
                                                                                                    	at android.widget.Toast.makeText(Toast.java:853)
                                                                                                    	at com.hacktivators.mentalhealth.YogaPageActivity$1.onResponse(YogaPageActivity.java:319)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by MohammedAbidNafi** [comment]
Add API key
